import asyncio
import sys
import traceback

from pyrogram import idle

import Bot as _bot_pkg
from Bot import bot, OWNER_ID, LOG
from Bot.utils.ffmpeg import check_ffmpeg_installed
from Bot.utils.telegram_helpers import Button, markup


async def main():
    LOG.info("Starting Erika-Amano Bot...")

    # Verify ffmpeg/ffprobe are actually installed and runnable before we
    # start accepting encode jobs. This doesn't stop the bot from starting
    # (other features -- auth, admin, stats -- still work without it), but
    # it logs a clear, actionable error immediately instead of only
    # surfacing as an opaque failure on the first user's encode.
    ffmpeg_ok, ffmpeg_msg = check_ffmpeg_installed()
    if ffmpeg_ok:
        LOG.info(ffmpeg_msg)
    else:
        LOG.critical(f"FFmpeg check failed: {ffmpeg_msg} Encoding will not work until this is fixed.")

    # Connect bot client
    await bot.start()
    me = await bot.get_me()
    LOG.info(f"Bot client connected as @{me.username}.")

    # Connect userbot if a SESSION_STRING was provided (used for >2GB
    # uploads). If it fails to connect, reset the package-level `ubot` to
    # None *before* plugins are imported below -- plugins do `from Bot import
    # ubot`, which copies the value at import time, so this ordering is what
    # makes the "fall back to the bot client" behavior actually take effect
    # instead of every large upload silently trying to use a dead client.
    if _bot_pkg.ubot:
        try:
            await _bot_pkg.ubot.start()
            LOG.info("Userbot (SESSION_STRING) connected for large uploads.")
        except Exception as e:
            LOG.warning(
                f"Error connecting userbot session: {e}. "
                "This usually means SESSION_STRING is not a valid Pyrogram "
                "session string -- e.g. it was generated by Telethon (a "
                "different, incompatible library), copied incompletely, or "
                "generated with a mismatched Pyrogram version. Generate a "
                "fresh one with Pyrogram itself (see .env.example). "
                "Falling back to the bot client for uploads (2GB limit); "
                "the bot will otherwise run normally."
            )
            _bot_pkg.ubot = None

    # Import plugins AFTER client connection (see comment above), so every
    # `@bot.on_message(...)` / `@bot.on_callback_query(...)` handler is
    # registered against live, connected clients.
    plugin_modules = [
        ("Bot.plugins.callback", "callback"),
        ("Bot.plugins.encoder", "encoder"),
        ("Bot.plugins.features", "features"),
        ("Bot.plugins.extra", "extra"),
        ("Bot.plugins.user_info", "user_info"),
        ("Bot.plugins.admin", "admin"),
        ("Bot.plugins.eval", "eval"),
    ]
    for module_path, name in plugin_modules:
        try:
            __import__(module_path)
            LOG.info(f"Loaded plugin: {name}")
        except Exception:
            LOG.error(f"Failed to load plugin {name}:\n{traceback.format_exc()}")

    # Client.add_handler() (called internally by every @bot.on_message /
    # @bot.on_callback_query decorator above) does NOT register synchronously
    # -- it schedules the actual registration as a task on the dispatcher's
    # event loop. Yield control briefly so those pending registrations
    # actually land in bot.dispatcher.groups before we report on them.
    await asyncio.sleep(0.5)

    total_handlers = sum(len(v) for v in bot.dispatcher.groups.values())
    LOG.info(f"Registered {total_handlers} handler(s) across {len(bot.dispatcher.groups)} group(s).")
    if total_handlers == 0:
        LOG.critical(
            "No handlers were registered! Commands will NOT work. "
            "Check the plugin load errors above."
        )

    # Auto-authorize owner in DB
    from Bot.plugins.database.mongo_db import owner_check
    await owner_check()

    # Resume any pending queue items from DB (restart resilience)
    try:
        from Bot.plugins.encoder import resume_pending_queue
        await resume_pending_queue()
        LOG.info("Pending queue check complete.")
    except Exception as e:
        LOG.warning(f"Queue resume failed: {e}")

    try:
        await bot.send_message(
            OWNER_ID,
            "**Bot Started Successfully!**",
            reply_markup=markup([
                [Button.inline("ʜᴇʟᴘ", b"answer_help"), Button.inline("ᴅᴇᴠᴇʟᴏᴘᴇʀ", b"answer_about_dev")],
            ]),
        )
    except Exception as e:
        LOG.warning(f"Could not send startup message: {e}")

    LOG.info("Bot is running. Press Ctrl+C to stop.")
    await idle()

    LOG.info("Shutting down...")
    try:
        await bot.stop()
    except Exception as e:
        LOG.warning(f"Error stopping bot client: {e}")
    if _bot_pkg.ubot:
        try:
            await _bot_pkg.ubot.stop()
        except Exception as e:
            LOG.warning(f"Error stopping userbot client: {e}")


if __name__ == "__main__":
    # IMPORTANT: use get_event_loop().run_until_complete(), NOT asyncio.run().
    #
    # Pyrogram's Dispatcher captures `self.loop = asyncio.get_event_loop()`
    # at Client-construction time (Bot/__init__.py creates `bot = Client(...)`
    # at import time, before this block runs) and schedules EVERYTHING --
    # every add_handler() call from a @bot.on_message decorator, and the
    # handler_worker tasks that actually consume incoming updates -- onto
    # that specific captured loop object via `self.loop.create_task(...)`.
    #
    # asyncio.run() always creates its OWN brand-new event loop internally,
    # completely separate from whatever get_event_loop() returned earlier.
    # Using it here would mean the Dispatcher's captured loop is never the
    # one actually running: outbound calls (get_me, send_message) still
    # work because they're plain awaited coroutines on the real running
    # loop, but every registered handler and the update-processing workers
    # would be scheduled on a dead loop that nothing ever drives -- the bot
    # connects and can send messages, but silently never processes any
    # incoming command or message.
    #
    # get_event_loop() call this reuses the SAME loop object that was
    # already current from the `bot = Client(...)` import above, so the
    # Dispatcher's internal scheduling and the loop we actually run here
    # are guaranteed to be identical.
    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(main())
    except KeyboardInterrupt:
        LOG.info("Bot stopped by user.")
    except Exception as e:
        LOG.critical(f"Fatal error: {e}")
        sys.exit(1)
